### ISSUE TITLE
Windows items glitchy, window controls not displaying - eOS

### ISSUE THREAD

**Issue by PretzelJones** [schemar/solarc-theme#19] opened 2018-02-19 22:15 UTC
On elementary (Gnome 3.18) items within windows don't display until moused-over. Also window controls are not displayed. They when clicked but do not appear.

**Comment by schemar** [comment] 2018-02-22 17:08
Are you sure this is a problem with the Solarc Theme? Did you try the Arc theme?

**Comment by PretzelJones** [comment] 2018-02-22 17:18
I can't recall whether the standard arc theme appears normal in elementary. I do know the OSX-Arc theme does. And elementary is listed as being supported by solarc.

**Comment by schemar** [comment] 2018-02-28 08:58
Right. The thing is that this is basically Arc with changed colors. So if the problem is with Arc in general, you can get help there. Maybe check if there is an issue already.

**Comment by PretzelJones** [comment] 2018-02-28 12:54
I loaded Arc and OSX Arc and both display correctly.

**Comment by schemar** [comment] 2018-03-01 18:38
Do you know if che problem is that it is accidentally the same color when not hovered? Can you provide screenshots of both states?

**Comment by schemar** [comment] 2019-08-29 10:42
Closing as outdated

**Closed as completed by schemar** 2019-08-29 10:42 UTC
