### ISSUE TITLE
Colour contrast in windows

### ISSUE THREAD

**Issue by natanvarga** [schemar/solarc-theme#16] opened 2017-04-10 21:05 UTC
Don't know if this is intentional in the sense that the colour choice just follows the solarized theme or something else, but sometimes texts in lighter foreground colour are a little bit hard to distinguish from the background. On the screenshot the title and menubars require extra effort to read because they are quite greyish. If this isn't going to be changed, I guess that's fine, but I wanted to point this out. 

![screenshot from 2017-04-10 22-56-16](https://cloud.githubusercontent.com/assets/6820797/24882615/fb62c8fe-1e41-11e7-9aca-4dc753474933.png)

**Comment by schemar** [comment] 2017-10-17 13:09
Hey @natanvarga that is not veyr easy to read, I agree. It should be fixed :+1: 
Can you create a pull request? You need to replace different colors in `solarize.sh`:
https://github.com/schemar/solarc-theme/blob/master/solarize.sh

**Comment by pushytoxin** [comment] 2018-12-04 10:54
I'm sorry to say, but in both cases the colors are wrong. The terminal body text has too much contrast, while the file browser has too litte.

See https://ethanschoonover.com/solarized/#usage-development
With solarized dark, the body text should be base0, but solarc sets it to base00.

**Comment by schemar** [comment] 2018-12-04 12:19
Hey @pushytoxin, thanks for the input 👍 
Would you be able to create a PR?

**Comment by pushytoxin** [comment] 2018-12-04 12:20
Already working on it.

**Comment by schemar** [comment] 2018-12-04 12:21
🤩

**Comment by pushytoxin** [comment] 2018-12-04 12:57
Just rewriting those values within solarize.sh doesn't seem to do the trick. What else do I need to do to modify the values?

My WIP branch is https://github.com/pushytoxin/solarc-theme/tree/patch-1

**Comment by pushytoxin** [comment] 2018-12-04 13:13
This is wrong, it's not going to work. The solarized.sh is replacing colors from the gtk colorscheme files using the arc colors, but they have already been replaced.

**Comment by pushytoxin** [comment] 2018-12-04 13:14
How do I reset the colors in the ~~gtkrc~~ scss files?

**Comment by pushytoxin** [comment] 2018-12-04 13:42
I resorted to moving the `common` directory from https://github.com/horst3180/arc-theme over to my solarc-theme dir.

Now all of the xfwm4 files are missing, so this can't be the right workflow.
OTOH, the GTK3 colors are fixed!!

**Comment by schemar** [comment] 2018-12-05 08:22
It should be as simple as modifying `solarize.sh`. When you look at the script it replaces colors in multiple places, incl. `.scss` files.

It could be that the original Arc theme does not differentiate in a color where Solarized should? In that case, simple replacement would not work 🤔

**Comment by pushytoxin** [comment] 2018-12-05 13:59
The usual way of installing (`./autogen.sh && sudo make install`) doesn't touch the `solarize.sh` script.

`solarize.sh` works by changing the original arc colors in the .scss, svg, xpm, etc.  by running `sed -i "s/${ARC_COLORS[$index]}/${SOLARIZED_COLORS[$index]}/Ig"`, but in this repo the colors are already solarized, so `sed` won't be able to change anything.

Am I missing something?

**Comment by schemar** [comment] 2018-12-05 17:05
You are right, sorry. If you want to test your changes, you should start with the original Arc colors.

**Comment by martinmeeser** [comment] 2019-02-08 14:43
First of all: Thanks sooo much for SolArc theme!
It is awesome!!

However using the SolArc Dark is really making me very tired, the contrast is too low, as described.

Just want to show how SolArc Dark in VS Code looks like (Menu items are much brighter !)

(left hand side is VS Code, right hand side is SolArc dark)

![image](https://user-images.githubusercontent.com/7906509/52485017-16529b00-2bb8-11e9-9714-38474ff5d0ec.png)

**Comment by schemar** [comment] 2019-02-08 15:42
That is true. Unfortunately I don't have time right now to improve it, but would love for someone to help out.

**Comment by martinmeeser** [comment] 2019-02-14 10:52
schemar: yes my time is more then limited, too.
As a workaround I am doing something that I have not done for years: I am using the light theme (solarc of course).

:-)

**Comment by Omnikron13** [comment] 2019-02-25 03:37
There's some issues with the GTK2 theme I need to have a fiddle with, but I hacked the solarize.sh script to pull a release from the Arc repo, patch that instead of the files from this repo and build it with some corrections for the contrast (along with adding xfwm4 asset rendering which seemed to be missing).

Here is the hacked solarize.sh if anyone else wants this theme: https://gist.github.com/Omnikron13/635bedab0c7a430f3bb172fd150be282

**Comment by schemar** [comment] 2019-02-25 09:41
🤩 Do you want to create a PR to be merged into this repo @Omnikron13 ?

**Comment by Omnikron13** [comment] 2019-02-25 23:08
Well what I have atm doesn't build themes for cinammon, gnome-shell, metacity or unity, as I'm not set up to test them anyway.

Also because my hacked version is patching a clean version of the Arc source I've also automated the autogen & make install step so it can then patch the index.theme files & directory names to say 'SolArc' instead of 'Arc' _after_ it spits out the finished themes.

All in all it's kinda hacky and just spits out themes to `build/usr/share/themes/SolArc(-darker|-dark)` rather than letting the user configure/make/install themselves, so I dunno if its that suitable to just be pulled in as is. (Not to mention that it ignores every other file in the repo, so I have no idea if I've missed some extra manual patching. =P)

**Comment by schemar** [comment] 2019-02-26 18:08
Hmm 🤔 What would help is the `solarized.sh` patch with the updated colors.

**Comment by Omnikron13** [comment] 2019-02-26 21:35
Sent a PR of the patch which sorted out the contrast issues I was seeing. 

I didn't come across an issue with base2/base3 getting used as text like in the original screenshot of a terminal here though (my terminal looks fine) so that specific issue isn't corrected afaik.

**Comment by schemar** [comment] 2019-02-27 09:21
Thank you! I will take a look when I have time, hopefully this weekend.

**Comment by bricewge** [comment] 2019-02-28 12:17
I can confirm that this issue isn't resolved by the PR #22. I just tried it and can't see any differences after applying the patches.

**Comment by Omnikron13** [comment] 2019-03-31 11:58
Sorry, I have been away for the last month. It should be noted that PR only changes the colours that solarize.sh attempts to patch with, so it doesn't resolve the issue mentioned by @pushytoxin :

> 
> 
> This is wrong, it's not going to work. The solarized.sh is replacing colors from the gtk colorscheme files using the arc colors, but they have already been replaced.

For solarize.sh to actually succeed in patching it needs to be run on clean copies of the Arc-theme source. I got around this issue in my fork by modifying solarize.sh to work from an empty directory and pull its own clean copy of the Arc-theme source before patching, but that is obviously way outside of the scope of this PR.

**Comment by schemar** [comment] 2019-04-01 10:34
Thanks for the feedback. I can apply the script to the original Arc colors, but I cannot make out which colors were actually changed in the script @Omnikron13 🤔

**Comment by Omnikron13** [comment] 2019-04-01 14:31
The main background colour is switched from base02 to the darker base03 and the primary text/fg is switched from base00 to the lighter base0 to try and match the base03:base0 contrast suggested by the [Usage & Development](https://ethanschoonover.com/solarized/#usage-development) notes for Solarized.

Additionally the secondary background colour is switched from base03 to base02, the suggested 'background highlight' colour, as used be e.g. the line numbers column in the vim theme.

There may be other less obvious tweaks required, but the themes that these changes build seem mostly good to me.

EDIT: I should note that I can only speak for the programs I've tested the themes with, with is primarily xfce programs and such, rather than the gnome desktop.

![example](https://user-images.githubusercontent.com/2133262/55336685-479f6700-5495-11e9-91d4-1477b019ebcc.png)

**Comment by schemar** [comment] 2019-04-01 15:58
The screenshot looks really good contrast wise 👍  Thanks a lot!
I merged your changes, but I still need to rebuild SolArc for the changes to take effect. I hope to do that this weekend.

**Comment by Omnikron13** [comment] 2019-08-18 15:05
I think we're calling this fixed now.

**Closed as completed by Omnikron13** 2019-08-18 15:05 UTC
